import React from 'react';
import MovieDetails from '@/components/Movies/MovieDetails';
import Navbar from '@/components/Navbar/Navbar';
import Movie from '@/db/model';
import Head from 'next/head';

function MovieDetail(props) {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <MovieDetails key={props.id} id={props.id} title={props.title} img={props.img} desc={props.desc} directedBy={props.directedBy} />
    </>
  )
}


export async function getStaticPaths() {
  const movies = await Movie.find({}, {_id: 1});
  
  const moviesIdParams = movies.map(movie => ({params: {movieId: movie._id.toString()}}));

  return {
    paths: moviesIdParams,
    fallback: 'blocking'
  }
}

export async function getStaticProps(context) {
  const movieId = context.params.movieId;

  const currMovie = JSON.parse(JSON.stringify(await Movie.findById(movieId)));


  return {
    props: {
      id: currMovie._id,
      title: currMovie.title,
      img: currMovie.img,
      desc: currMovie.desc,
      directedBy: currMovie.directedBy
    }
  }
}


export default MovieDetail;