import MovieList from '@/components/Movies/MovieList';
import Navbar from '@/components/Navbar/Navbar';
import Loading from '@/components/UI/Loading';
import Head from 'next/head';
import React, { useState } from 'react';

function Movies() {
    const [loading, setLoading] = useState(false);
    function loadingHandler(isTrue) {
        setLoading(isTrue);
    }

    return (
        <>
            <Head>
                <title>Flixion | MoviesList</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            {loading ? <Loading /> :
                <MovieList onLoad={loadingHandler} />
            }
        </>
    )
}

export default Movies;